### Use the following code for the questions below:

`a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])`

In [83]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### 1. How many negative numbers are there?

In [84]:
negatives = a[a < 0]
len(negatives)

4

### 2. How many positive numbers are there?

In [85]:
positives = a[a > 0]
len(positives)

5

### 3. How many even positive numbers are there?

In [87]:
even_positives = positives[positives % 2 == 0]
len(even_positives)

3

### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [88]:
add_three = a + 3
positives = add_three[add_three > 0]
len(positives)

10

### 5. If you squared each number, what would the new mean and standard deviation be?

In [13]:
squared = a ** 2
squared.mean(), squared.std()

(74.0, 144.0243035046516)

### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [17]:
centered = a - a.mean()
centered, centered.mean()

(array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
        -10.]),
 0.0)

In [18]:
z_scores = (a - a.mean()) / a.std()
z_scores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [89]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
print(f"sum_of_a:  {sum_of_a}")

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
print(f"min_of_a:  {min_of_a}")

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
print(f"max_of_a:  {max_of_a}")

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum_of_a / len(a)
print(f"mean_of_a:  {mean_of_a}")

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = 1
for num in a:
    product_of_a *= num
    
print(f"product_of_a:  {product_of_a}")

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [n ** 2 for n in a]
    
print(f"squares_of_a:  {squares_of_a}")

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = [num for num in a if num % 2 != 0]
print(f"odds_in_a:  {odds_in_a}")

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = [num for num in a if num % 2 == 0]
print(f"evens_in_a:  {evens_in_a}")

sum_of_a:  55
min_of_a:  1
max_of_a:  10
mean_of_a:  5.5
product_of_a:  3628800
squares_of_a:  [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
odds_in_a:  [1, 3, 5, 7, 9]
evens_in_a:  [2, 4, 6, 8, 10]


In [92]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
b = np.array(b)
sum_of_b = b.sum()
print(f"sum_of_b:  {sum_of_b}")

# Exercise 2 - refactor the following to use numpy. 
min_of_b = b.min()
print(f"min_of_b:  {min_of_b}")

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = b.max()
print(f"max_of_b:  {max_of_b}")

# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = b.mean()
print(f"mean_of_b:  {mean_of_b}")

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = np.prod(b)
print(f"product_of_b:  {product_of_b}")

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = b ** 2
print(f"squares_of_b:  {squares_of_b}")

# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = b[b % 2 != 0]
print(f"odds_in_b:  {odds_in_b}")

# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = b[b % 2 == 0]
print(f"evens_in_b: {evens_in_b}")

# Exercise 9 - print out the shape of the array b.
print(f"shape of b:  {b.shape}")

# Exercise 10 - transpose the array b.
print(f"b transposed:  {np.transpose(b)}")
# can also call transpose and reshape directly on array

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
print(f"b reshaped 1x6:  {np.reshape(b, (1, 6))}")

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
print(f"b reshaped 6x1:  {np.reshape(b, (6, 1))}")

sum_of_b:  33
min_of_b:  3
max_of_b:  8
mean_of_b:  5.5
product_of_b:  20160
squares_of_b:  [[ 9 16 25]
 [36 49 64]]
odds_in_b:  [3 5 7]
evens_in_b: [4 6 8]
shape of b:  (2, 3)
b transposed:  [[3 6]
 [4 7]
 [5 8]]
b reshaped 1x6:  [[3 4 5 6 7 8]]
b reshaped 6x1:  [[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [64]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
c = np.array(c)

# Exercise 1 - Find the min, max, sum, and product of c.
print(c.min(), c.max(), c.sum(), np.prod(c))

# Exercise 2 - Determine the standard deviation of c.
print(c.std())

# Exercise 3 - Determine the variance of c.
print(np.var(c))

# Exercise 4 - Print out the shape of the array c
print(c.shape)

# Exercise 5 - Transpose c and print out transposed result.
transposed_c = np.transpose(c)
print(transposed_c)

# Exercise 6 - Get the dot product of the array c with c. 
print(np.dot(c, c))

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
print(np.array(c * transposed_c).sum())

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
print(np.prod(np.array(c * transposed_c)))

1 9 45 362880
2.581988897471611
6.666666666666667
(3, 3)
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
261
131681894400


In [81]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)
# Exercise 1 - Find the sine of all the numbers in d
print(np.sin(d))

# Exercise 2 - Find the cosine of all the numbers in d
print(np.cos(d))

# Exercise 3 - Find the tangent of all the numbers in d
print(np.tan(d))

# Exercise 4 - Find all the negative numbers in d
print(d[d < 0])

# Exercise 5 - Find all the positive numbers in d
print(d[d > 0])

# Exercise 6 - Return an array of only the unique numbers in d.
print(np.unique(d))

# Exercise 7 - Determine how many unique numbers there are in d.
print(len(np.unique(d)))

# Exercise 8 - Print out the shape of d.
print(d.shape)

# Exercise 9 - Transpose and then print out the shape of d.
transpose_d = np.transpose(d)
print(transpose_d.shape)

# Exercise 10 - Reshape d into an array of 9 x 2
np.reshape(d, (9, 2))

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]
[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]
[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]
[-90 -30 -45 -45]
[ 90  30  45 120 180  45 270  90  60  45  90 180]
[-90 -45 -30   0  30  45  60  90 120 180 270]
11
(3, 6)
(6, 3)


array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])